export {default as Login} from './Login'
export {default as NotFound} from './NotFound'
export {default as DashBoard} from './DashBoard'
export {default as Setting} from './Setting'
export {default as Foods} from './Foods'