export {default as Login} from './Login'
export {default as NotFound} from './NotFound'
export {default as DashBoard} from './DashBoard'
export {default as Setting} from './Setting'
export {default as Foods} from './Foods'
export {default as AddFood} from './AddFood'
export {default as UpdateFood} from './UpdateFood'